#!/bin/sh /etc/rc.common
# Based on the OpenWrt example script
# Copyright (C) 2007 OpenWrt.org

START=99
STOP=99

start() {
        echo Starting Radio API...
	sleep 5
	cd /usr/bin/radioApi
	/usr/bin/radioApi/radioApi
	echo Radio API started!
        # commands to launch application
}

stop() {
        echo stop
	killall radioApi
        # commands to kill application
}
